### PR TITLE
Add istio scheme to gardener resource manager for reversed vpn setup.

### PR DESCRIPTION
**Pull request by DockToFuture**
Co-authored-by: Johannes Scheerer <johannes.scheerer@sap.com>

**How to categorize this PR?**

/area networking
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Scheme is required for https://github.com/gardener/gardener/pull/3812.

**Release note**:

```other operator
none
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Out of curiosity: Why is this needed/what do you plan to do with GRM as part of https://github.com/gardener/gardener/pull/3812?

**Comment by timebertt** [comment]
I don't like that grm is now also depending on the istio APIs.
I already don't like, that it is depending on the hvpa/vpa stuff and so on.

Generally speaking, grm can be used for any kind of resource (e.g. also istio crds) even if they are not part of grm's scheme.
Using typed objects instead of `unstructured.Unstructured` is just a caching optimization, but is not strictly required.
If caching is super important for your use case, we can also think about caching unstructured objects somehow.

**Comment by DockToFuture** [comment]
We are seeing the following info messages in the grm if we don't add the istio scheme, which seems a little bit confusing. Therefore we thought it would be better to add the scheme. But if can ignore the log messages, we can leave it as is.

`{"level":"info","ts":"2021-04-15T11:12:30.314Z","logger":"controller-runtime.manager.health-controller","msg":"could not create new object of kind for health checks (probably not registered in the used scheme), falling back to unstructured request","object":"shoot--dev--shoot-gcp-cal/vpn-seed-server","GroupVersionKind":"networking.istio.io/v1beta1, Kind=DestinationRule","error":"no kind \"DestinationRule\" is registered for version \"networking.istio.io/v1beta1\" in scheme \"github.com/gardener/gardener-resource-manager/pkg/cmd/target.go:144\""}

{"level":"info","ts":"2021-04-15T11:12:30.516Z","logger":"controller-runtime.manager.health-controller","msg":"could not create new object of kind for health checks (probably not registered in the used scheme), falling back to unstructured request","object":"shoot--dev--shoot-gcp-cal/vpn-seed-server","GroupVersionKind":"networking.istio.io/v1beta1, Kind=Gateway","error":"no kind \"Gateway\" is registered for version \"networking.istio.io/v1beta1\" in scheme \"github.com/gardener/gardener-resource-manager/pkg/cmd/target.go:144\""}

{"level":"info","ts":"2021-04-15T11:12:30.614Z","logger":"controller-runtime.manager.health-controller","msg":"could not create new object of kind for health checks (probably not registered in the used scheme), falling back to unstructured request","object":"shoot--dev--shoot-gcp-cal/vpn-seed-server","GroupVersionKind":"networking.istio.io/v1beta1, Kind=VirtualService","error":"no kind \"VirtualService\" is registered for version \"networking.istio.io/v1beta1\" in scheme \"github.com/gardener/gardener-resource-manager/pkg/cmd/target.go:144\""}`

**Comment by rfranzke** [comment]
OK, it seems you are using GRM in the seed to create these resources. It rather fits to the PR in g/g, but now that we talk about it, what about rather following what other components do (e.g., https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/kubescheduler/kube_scheduler.go#L146-L160)? They are not using GRM but directly crupating the resources in the seed while GRM is only used for resources in the shoot.

**Comment by DockToFuture** [comment]
We changed it, therefore we can close this PR. Tests are adapted as well!

**Pull request closed without merging**
