### PR TITLE
vendor g/g@1.17.0 and configurable resource lock

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area scalability
/kind enhancement
/priority normal

**What this PR does / why we need it**:

This PR makes the leader election resource lock of grm configurable by vendoring `g/g@v1.17.0` and adding the command line flag `--leader-election-resource-lock` and chart value `leaderElection.resourceLock`.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener-resource-manager/issues/77

**Special notes for your reviewer**:

**Release note**:

```feature operator
It is now possible to specify the leader election resource lock via the command line flag `--leader-election-resource-lock` (defaults to `configmapsleases`) and the chart value `leaderElection.resourceLock`. Please be careful when changing the resource lock and always migrate via multilocks in order to prevent situations where multiple instances of the controller are running with leader election and thus acting on the same resources.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by timebertt** [comment]
Pushed one more commit to make the leader election resource lock configurable. 
This was the reason for vendoring in the first place (I almost forgot 😄)...

**Comment by timebertt** [comment]
Waiting for `g/g@v1.17.1` including https://github.com/gardener/gardener/pull/3611.

Ref https://concourse.ci.gardener.cloud/builds/539404#L603356b3:29:35:
```
> Generate / Vendor Check
Error during calling make clean: make[1]: Entering directory '/go/src/github.com/gardener/gardener-resource-manager'
> Clean
find: './hack/api-reference/': No such file or directory
make[1]: *** [/go/src/github.com/gardener/gardener-resource-manager/Makefile:84: clean] Error 1
make[1]: Leaving directory '/go/src/github.com/gardener/gardener-resource-manager'
make: *** [Makefile:88: check-generate] Error 1
```

**Comment by timebertt** [comment]
Ok, vendored https://github.com/gardener/gardener/pull/3611 now.
@rfranzke PTAL.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
