### PR TITLE
Revendor several dependencies

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Revendor several dependencies

**Special notes for your reviewer**:
/squash

**Release note**:

```noteworthy developer
Most dependencies have been revendored, most prominently:
* `github.com/gardener/gardener@v1.26.1`
* `k8s.io/*@v0.21.2`
* `sigs.k8s.io/controller-runtime@v0.9.1`
```

### CODE REVIEW

**Comment by timebertt** [comment]
```
>> make generate
make generate needs to be run:
 M pkg/mock/controller-runtime/manager/mocks.go
make: *** [Makefile:89: check-generate] Error 1
```

**Comment by rfranzke** [comment]
@timebertt fixed with cc0348b

**Review by timebertt — COMMENTED** [review]
Nicely done! Thank you :)

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
